# Based on https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html
name: Sync Two Wiki Repos
on:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

        # Setup Git
      - run: git config user.name "typescript-bot"
      - run: git config user.email "bot@typescriptlang.org"

        # Add the authed remotes for .
      - run:  git remote add upstream https://$GITHUB_TOKEN@github.com/microsoft/TypeScript.wiki.git > /dev/null 2>&1
        env:
          GITHUB_TOKEN: ${{ secrets.TS_BOT_TOKEN }}

      # Update search links from the origin repo before pushing to the upstream
      - run: git clone --depth 1 https://github.com/microsoft/TypeScript.git
      - run: npm i
      - run: node scripts/convertRelativeLinksToHardcoded.js **/*.md --write
      - run: rm -rf TypeScript

      - run: git add .
      - run: git commit --amend --no-edit

        # Push to the auth'd branch
      - run:  git push upstream HEAD:master -f > /dev/null 2>&1
