# Based on https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html
name: Sync Two Wiki Repos
on:
  push:
    branches: [master]

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
    
        # Setup Git
      - run: git config user.name "typescript-bot"
      - run: git config user.email "bot@typescriptlang.org"
        # Remove the un-auth'd origin
      - run:  git remote remove origin
        # Switch to authed remotes for both the - and the .
      - run: |
           git remote add origin https://$GITHUB_TOKEN@github.com/microsoft/TypeScript-wiki.git > /dev/null 2>&1
           git remote add upstream https://$GITHUB_TOKEN@github.com/microsoft/TypeScript.wiki.git > /dev/null 2>&1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: git fetch origin
      - run: git fetch upstream
        # Merge them all together
      - run:  git merge upstream/master --no-edit
        # Push them both
      - run:  git push upstream HEAD:master > /dev/null 2>&1
